apiVersion: v1
kind: ConfigMap
metadata:
  name: alert-rules
  labels:
    app: prometheus
data:
  alert.rules: |-
    groups:
      - name: fortify
        rules:
          # Disk Space Usage
          - alert: DiskSpaceUsageHigh
            expr: (node_filesystem_size_bytes{fstype!~"tmpfs|aufs"} - node_filesystem_free_bytes{fstype!~"tmpfs|aufs"}) / node_filesystem_size_bytes{fstype!~"tmpfs|aufs"} > 0.85
            for: 5m
            labels:
              severity: critical

          # RAM Consumption
          - alert: HighMemoryUsage
            expr: (1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes)) > 0.85
            for: 5m
            labels:
              severity: critical

          # CPU Consumption
          - alert: HighCPUUsage
            expr: rate(node_cpu_seconds_total{mode="idle"}[5m]) / rate(node_cpu_seconds_total[5m]) < 0.15
            for: 5m
            labels:
              severity: critical

          # Pod Health
          - alert: PodUnhealthy
            expr: kube_pod_status_phase{phase!="Running"} > 0
            for: 5m
            labels:
              severity: critical

          # Cluster Health
          - alert: ClusterUnavailable
            expr: kube_node_status_condition{condition="Ready", status="false"} > 0
            for: 5m
            labels:
              severity: critical
