{{- if .Values.alertmanager.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: alertmanager
  labels:
    app: alertmanager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alertmanager
  template:
    metadata:
      labels:
        app: alertmanager
    spec:
      containers:
        - name: alertmanager
          image: "{{ .Values.alertmanager.image.repository }}:{{ .Values.alertmanager.image.tag }}"
          imagePullPolicy: {{ .Values.alertmanager.image.pullPolicy }}
          ports:
            - containerPort: 9093
          resources:
            {{- toYaml .Values.alertmanagerResources | nindent 12 }}
          volumeMounts:
            - name: alertmanager-config-volume
              mountPath: /etc/alertmanager/
              subPath: alertmanager.yml
      volumes:
        - name: alertmanager-config-volume
          configMap:
            name: alertmanager-config
{{- end }}

