apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "prometheus.fullname" . }}-config
  labels:
    {{- include "prometheus.labels" . | nindent 4 }}
data:
  prometheus.yml: |-
    global:
      scrape_interval: 15s
      evaluation_interval: 15s
      external_labels:
        monitor: 'prometheus'
    alerting:
      alertmanagers:
      - static_configs:
        - targets: ['{{ include "prometheus.fullname" . }}-alertmanager:9093']
    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']
      {{ toYaml .Values.scrapeConfigs | indent 6 }}

