apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "centralized-monitoring.fullname" . }}-alertmanager-config
  labels:
    {{- include "centralized-monitoring.labels" . | nindent 4 }}
data:
  alertmanager.yml: |-
    {{ .Values.alertmanager.config | indent 4 }}

