apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-prometheus-config
  labels:
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/instance: prometheus
    app.kubernetes.io/managed-by: Helm
data:
  prometheus.yml: |-
    global:
      scrape_interval: 15s
      evaluation_interval: 15s
      external_labels:
        monitor: 'prometheus'
    
    alerting:
      alertmanagers:
        - static_configs:
            - targets: ['prometheus-alertmanager:9093']
    
    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']
      
      - job_name: 'node-exporter'
        kubernetes_sd_configs:
          - role: endpoints
        relabel_configs:
          - action: keep
            regex: node-exporter
            source_labels:
              - __meta_kubernetes_service_label_app

      - job_name: 'kubernetes-pods'
        kubernetes_sd_configs:
          - role: pod
        relabel_configs:
          - action: labelmap
            regex: __meta_kubernetes_pod_label_(.+)
          - action: replace
            target_label: job
            replacement: kubernetes-pods
