apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "prometheus.fullname" . }}-alertmanager-config
  labels:
    {{- include "prometheus.labels" . | nindent 4 }}
data:
  alertmanager.yml: |-
    {{ .Values.alertmanager.config | indent 4 }}

