apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-alertmanager-config
  labels:
    app.kubernetes.io/name: alertmanager
    app.kubernetes.io/instance: alertmanager
    app.kubernetes.io/version: "v0.23.0"
    app.kubernetes.io/managed-by: Helm
data:
  alertmanager.yml: |-
    route:
      group_by: ['job']
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 12h
      receiver: 'default'
    receivers:
    - name: 'default'
      webhook_configs:
      - url: 'http://example.com/'

