apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "prometheus.fullname" . }}-node-exporter
  labels:
    {{- include "node-exporter.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "node-exporter.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "node-exporter.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: node-exporter
          image: "{{ .Values.image.nodeExporter.repository }}:{{ .Values.image.nodeExporter.tag }}"
          imagePullPolicy: {{ .Values.image.nodeExporter.pullPolicy }}
          ports:
            - containerPort: 9100
          resources:
            {{- toYaml .Values.resources.nodeExporter | nindent 12 }}
          volumeMounts:
            - name: proc
              mountPath: /host/proc
              readOnly: true
            - name: sys
              mountPath: /host/sys
              readOnly: true
            - name: root
              mountPath: /rootfs
              readOnly: true
      volumes:
        - name: proc
          hostPath:
            path: /proc
        - name: sys
          hostPath:
            path: /sys
        - name: root
          hostPath:
            path: /

