apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "centralized-monitoring.fullname" . }}-alertmanager
  labels:
    {{- include "centralized-monitoring.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "centralized-monitoring.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "centralized-monitoring.selectorLabels" . | nindent 8 }}
    spec:
      securityContext:
        fsGroup: {{ .Values.securityContext.fsGroup }}
      containers:
        - name: alertmanager
          image: "{{ .Values.image.alertmanager.repository }}:{{ .Values.image.alertmanager.tag }}"
          imagePullPolicy: {{ .Values.image.alertmanager.pullPolicy }}
          ports:
            - containerPort: 9093
          volumeMounts:
            - name: config-volume
              mountPath: /etc/alertmanager
            - name: data
              mountPath: /alertmanager
          resources:
            {{- toYaml .Values.resources.alertmanager | nindent 12 }}
      volumes:
        - name: config-volume
          configMap:
            name: {{ include "centralized-monitoring.fullname" . }}-alertmanager-config
        - name: data
          emptyDir: {}  # or use `hostPath` if needed

