apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "prometheus.fullname" . }}-prometheus
  labels:
    {{- include "prometheus.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "prometheus.fullname" . }}-prometheus
  minReplicas: {{ .Values.hpa.prometheus.minReplicas }}
  maxReplicas: {{ .Values.hpa.prometheus.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.hpa.prometheus.cpu }}

