{{- if .Values.nodeExporter.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: node-exporter
  labels:
    app: node-exporter
spec:
  ports:
    - port: 9100
      targetPort: 9100
      protocol: TCP
      name: http
  selector:
    app: node-exporter
{{- end }}

