apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "prometheus.fullname" . }}
  namespace: {{ .Values.namespace }}
rules:
  - apiGroups: [""]
    resources: ["pods", "services", "endpoints"]
    verbs: ["get", "list", "watch"]

