apiVersion: v1
kind: Service
metadata:
  name: {{ include "prometheus.fullname" . }}-node-exporter
  labels:
    {{- include "prometheus.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 9100
      targetPort: 9100
      protocol: TCP
      name: http
  selector:
    {{- include "prometheus.selectorLabels" . | nindent 4 }}

