apiVersion: v1
kind: Service
metadata:
  name: {{ include "prometheus.fullname" . }}-alertmanager
  labels:
    {{- include "alertmanager.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 9093
      protocol: TCP
      name: http
  selector:
    {{- include "alertmanager.selectorLabels" . | nindent 4 }}

